spring:
  application:
    name: consumer

server:
  port: 8002

eureka:
  instance:
    #注册服务的时候使用IP地址
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/